"""empty message

Revision ID: 0dc57e394f56
Revises: 10040d819d77
Create Date: 2020-05-10 16:48:46.208165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc57e394f56'
down_revision = '10040d819d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nesticProduccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planchas_cortadas', sa.Integer(), nullable=True),
    sa.Column('ot_cortada', sa.Integer(), nullable=True),
    sa.Column('operador', sa.String(length=100), nullable=False),
    sa.Column('nestic_cortado', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nesticProduccion')
    # ### end Alembic commands ###
