"""empty message

Revision ID: 10040d819d77
Revises: 
Create Date: 2020-05-09 22:53:07.955288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10040d819d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(length=100), nullable=False),
    sa.Column('numero_ot', sa.Integer(), nullable=True),
    sa.Column('cantiadUnidadesFabricarEnLaOt', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modeloProduccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_produccion', sa.String(length=100), nullable=False),
    sa.Column('ot_produccion', sa.Integer(), nullable=True),
    sa.Column('cantidad_producir', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nestic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_nestic', sa.String(length=100), nullable=False),
    sa.Column('numero_piezas_criticas', sa.Integer(), nullable=True),
    sa.Column('tiempo_corte', sa.Integer(), nullable=True),
    sa.Column('espesor', sa.Integer(), nullable=True),
    sa.Column('longitud_nestic', sa.Integer(), nullable=True),
    sa.Column('modelo_elegido', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_elegido'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_pieza', sa.String(length=100), nullable=False),
    sa.Column('cantidadPiezasPorPlancha', sa.Integer(), nullable=True),
    sa.Column('crearLongitudCortePieza', sa.Integer(), nullable=True),
    sa.Column('nesticElegido', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nesticElegido'], ['nestic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piezas')
    op.drop_table('nestic')
    op.drop_table('modeloProduccion')
    op.drop_table('modelo')
    # ### end Alembic commands ###
