"""empty message

Revision ID: 3079fe3e08b9
Revises: 3ed2f7ff1906
Create Date: 2020-05-20 18:07:09.462535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3079fe3e08b9'
down_revision = '3ed2f7ff1906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produccionProductoTerminado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_seleccionada', sa.Integer(), nullable=True),
    sa.Column('sub_producto_seleccionado', sa.String(length=100), nullable=False),
    sa.Column('producto_terminado_utilizado_estufa', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produccionProductoTerminado')
    # ### end Alembic commands ###
