"""empty message

Revision ID: 32830709a06e
Revises: 5bdda34b1926
Create Date: 2020-05-15 23:01:59.887163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32830709a06e'
down_revision = '5bdda34b1926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piezasIntegranSubProducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subProductoSeleccionado', sa.String(length=100), nullable=False),
    sa.Column('piezaSeleccionaIntegraSubproducto', sa.String(length=100), nullable=False),
    sa.Column('subProducto_ot_seleccionado', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piezasIntegranSubProducto')
    # ### end Alembic commands ###
