"""empty message

Revision ID: 3ed2f7ff1906
Revises: cf82ceaffe31
Create Date: 2020-05-19 20:27:51.068505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed2f7ff1906'
down_revision = 'cf82ceaffe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piezasIntegranProductoTerminado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_seleccionada', sa.Integer(), nullable=True),
    sa.Column('sub_producto_seleccionado', sa.String(length=100), nullable=False),
    sa.Column('producto_terminado_utilizado_estufa', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piezasIntegranProductoTerminado')
    # ### end Alembic commands ###
