"""empty message

Revision ID: 53f41b847ff5
Revises: 8a2e25cdeb32
Create Date: 2020-05-14 16:24:53.832078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f41b847ff5'
down_revision = '8a2e25cdeb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plegado', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plegado', 'date_created')
    # ### end Alembic commands ###
