"""empty message

Revision ID: 5bdda34b1926
Revises: 76b18e51575f
Create Date: 2020-05-15 21:09:51.440293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdda34b1926'
down_revision = '76b18e51575f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subproducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Linea1NombreSubproducto', sa.String(length=100), nullable=False),
    sa.Column('subProducto_ot_seleccionado', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subproducto')
    # ### end Alembic commands ###
