"""empty message

Revision ID: 76b18e51575f
Revises: 53f41b847ff5
Create Date: 2020-05-15 12:52:56.948567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b18e51575f'
down_revision = '53f41b847ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pintura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pintura_ot_seleccionado', sa.Integer(), nullable=True),
    sa.Column('pinturaPiezaSeleccionada', sa.String(length=100), nullable=False),
    sa.Column('pinturaCantidadPiezas', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pintura')
    # ### end Alembic commands ###
