"""empty message

Revision ID: 8a2e25cdeb32
Revises: 5a6f3d55aaa8
Create Date: 2020-05-14 16:21:38.477462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2e25cdeb32'
down_revision = '5a6f3d55aaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plegado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plegado_ot_seleccionado', sa.Integer(), nullable=True),
    sa.Column('plegadoPiezaSeleccionada', sa.String(length=100), nullable=False),
    sa.Column('plegadoMaquinaSeleccionada', sa.String(length=100), nullable=False),
    sa.Column('plegadoOperadorSeleccionado', sa.String(length=100), nullable=False),
    sa.Column('plegadoCantidadPiezas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plegado')
    # ### end Alembic commands ###
