"""empty message

Revision ID: a5cc4fed23d4
Revises: 32830709a06e
Create Date: 2020-05-16 13:27:07.851645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cc4fed23d4'
down_revision = '32830709a06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piezasIntegranSubProducto', sa.Column('cantidad_utilizada_por_subproducto', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piezasIntegranSubProducto', 'cantidad_utilizada_por_subproducto')
    # ### end Alembic commands ###
