"""empty message

Revision ID: cf82ceaffe31
Revises: a5cc4fed23d4
Create Date: 2020-05-16 14:09:22.298522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf82ceaffe31'
down_revision = 'a5cc4fed23d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ot_seleccionada', sa.Integer(), nullable=True),
    sa.Column('sub_producto_seleccionado', sa.String(length=100), nullable=False),
    sa.Column('produccion_Cantidad_fabricada', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produccion')
    # ### end Alembic commands ###
