"""empty message

Revision ID: fadd3388d7bb
Revises: 
Create Date: 2020-05-04 22:30:04.814109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadd3388d7bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(length=100), nullable=False),
    sa.Column('numero_ot', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nestic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_nestic', sa.String(length=100), nullable=False),
    sa.Column('numero_piezas_criticas', sa.String(length=100), nullable=False),
    sa.Column('tiempo_corte', sa.String(length=100), nullable=False),
    sa.Column('espesor', sa.String(length=100), nullable=False),
    sa.Column('longitud_nestic', sa.String(length=100), nullable=False),
    sa.Column('modelo_elegido', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_elegido'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiempo_corte')
    )
    op.create_table('piezas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_pieza', sa.String(length=100), nullable=False),
    sa.Column('cantidadPiezasPorPlancha', sa.String(length=100), nullable=False),
    sa.Column('crearLongitudCortePieza', sa.String(length=100), nullable=False),
    sa.Column('nesticElegido', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nesticElegido'], ['nestic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crearLongitudCortePieza')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piezas')
    op.drop_table('nestic')
    op.drop_table('modelo')
    # ### end Alembic commands ###
